"""empty message

Revision ID: 0163bb7aaefb
Revises: 77535936ca0a
Create Date: 2025-01-05 18:09:28.734129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0163bb7aaefb'
down_revision = '77535936ca0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('company')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
