"""empty message

Revision ID: 68c57731afc6
Revises: 0163bb7aaefb
Create Date: 2025-01-06 12:50:54.143505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c57731afc6'
down_revision = '0163bb7aaefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('internal_note', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_item', schema=None) as batch_op:
        batch_op.drop_column('internal_note')

    # ### end Alembic commands ###
