"""empty message

Revision ID: 714da15465d5
Revises: 68c57731afc6
Create Date: 2025-02-01 16:33:24.190143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '714da15465d5'
down_revision = '68c57731afc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_status', sa.String(length=255), nullable=False, server_default='pte-envio'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('shipping_status')

    # ### end Alembic commands ###
