"""empty message

Revision ID: d8858edc74d4
Revises: 0a10f6aa0cd0
Create Date: 2024-11-09 10:00:02.755565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8858edc74d4'
down_revision = '0a10f6aa0cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_create')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_create', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
