"""empty message

Revision ID: ea2625115f00
Revises: d8858edc74d4
Create Date: 2024-11-09 11:26:27.300725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea2625115f00'
down_revision = 'd8858edc74d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variation_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('tax_class', sa.String(length=255), nullable=True),
    sa.Column('subtotal', sa.String(length=255), nullable=False),
    sa.Column('subtotal_tax', sa.String(length=255), nullable=False),
    sa.Column('total', sa.String(length=255), nullable=False),
    sa.Column('total_tax', sa.String(length=255), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('line_item')
    # ### end Alembic commands ###
